# Generated by Django 3.2.6 on 2024-11-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulgarian_meteo_pro', '0002_auto_20241102_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulgarianmeteoprodata',
            name='station_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
