# Generated by Django 3.2.6 on 2024-11-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('bulgarian_meteo_pro', '0003_alter_bulgarianmeteoprodata_station_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulgarianmeteoprodata',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bulgarian_meteo_pro_data', to='stations.station'),
        ),
    ]
