# Generated by Django 3.2.6 on 2024-11-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
