# Generated by Django 3.2.6 on 2024-11-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(help_text='City where the station is located', max_length=100)),
                ('coordinates', models.OneToOneField(help_text='Coordinates of the location', on_delete=django.db.models.deletion.CASCADE, to='weather_master_x.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_fahrenheit', models.FloatField(help_text='Temperature in Fahrenheit')),
                ('humidity_percent', models.FloatField(help_text='Humidity as a percentage')),
                ('pressure_hpa', models.FloatField(help_text='Atmospheric pressure in hPa')),
                ('uv_index', models.IntegerField(help_text='UV index')),
                ('rain_mm', models.FloatField(help_text='Rainfall in millimeters')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherMasterX',
            fields=[
                ('station_identifier', models.CharField(help_text='Unique identifier of the station', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('recorded_at', models.DateTimeField(help_text='Timestamp of the data in ISO 8601 format')),
                ('operational_status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance')], default='operational', help_text='Operational status of the station', max_length=20)),
                ('location', models.OneToOneField(help_text='Location of the station', on_delete=django.db.models.deletion.CASCADE, to='weather_master_x.location')),
                ('readings', models.OneToOneField(help_text='Readings of various parameters at the station', on_delete=django.db.models.deletion.CASCADE, to='weather_master_x.readings')),
            ],
        ),
    ]
